"""empty message

Revision ID: 07bf47f4fc50
Revises: e18e3abf5229
Create Date: 2023-12-28 00:34:09.522328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07bf47f4fc50'
down_revision = 'e18e3abf5229'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('song_baskets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('track_id', sa.String(), nullable=True),
    sa.Column('playlist_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], name=op.f('fk_song_baskets_playlist_id_playlists')),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], name=op.f('fk_song_baskets_track_id_tracks')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_song_baskets_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['refresh_token'])
        batch_op.create_unique_constraint(None, ['access_token'])
        batch_op.create_unique_constraint(None, ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    op.drop_table('song_baskets')
    # ### end Alembic commands ###
