"""empty message

Revision ID: 2ed647f4f848
Revises: d15943e22ce3
Create Date: 2024-01-02 00:56:48.781964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ed647f4f848'
down_revision = 'd15943e22ce3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('basket_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_songs_basket_id_song_baskets'), 'song_baskets', ['basket_id'], ['basket_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_songs_basket_id_song_baskets'), type_='foreignkey')
        batch_op.drop_column('basket_id')

    # ### end Alembic commands ###
