"""empty message

Revision ID: 444ce7f3a5cb
Revises: 86a09f95a325
Create Date: 2023-12-30 22:59:56.960400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '444ce7f3a5cb'
down_revision = '86a09f95a325'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_songs',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('song_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['song_id'], ['songs.track_id'], name=op.f('fk_user_songs_song_id_songs')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_songs_user_id_users'))
    )
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.alter_column('track_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_constraint('fk_songs_song_basket_id_song_baskets', type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('song_basket_id')
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('song_basket_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.VARCHAR(), nullable=True))
        batch_op.create_foreign_key('fk_songs_song_basket_id_song_baskets', 'song_baskets', ['song_basket_id'], ['id'])
        batch_op.alter_column('track_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    op.drop_table('user_songs')
    # ### end Alembic commands ###
