"""empty message

Revision ID: 50ae7fac4658
Revises: 
Create Date: 2024-01-05 09:53:57.649071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50ae7fac4658'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('profile_pic', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('song_baskets',
    sa.Column('basket_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('playlist_name', sa.String(), nullable=True),
    sa.Column('playlist_description', sa.String(), nullable=True),
    sa.Column('playlist_img', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_song_baskets_user_id_users')),
    sa.PrimaryKeyConstraint('basket_id')
    )
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('access_token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('refresh_token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tokens_user_id_users')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_token'),
    sa.UniqueConstraint('refresh_token'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.String(), nullable=True),
    sa.Column('track_name', sa.String(), nullable=True),
    sa.Column('track_image', sa.String(), nullable=True),
    sa.Column('track_album', sa.String(), nullable=True),
    sa.Column('track_artist', sa.String(), nullable=True),
    sa.Column('track_uri', sa.String(), nullable=True),
    sa.Column('basket_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['basket_id'], ['song_baskets.basket_id'], name=op.f('fk_songs_basket_id_song_baskets')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('song_basket_association',
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('basket_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['basket_id'], ['song_baskets.basket_id'], name=op.f('fk_song_basket_association_basket_id_song_baskets')),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], name=op.f('fk_song_basket_association_song_id_songs')),
    sa.PrimaryKeyConstraint('song_id', 'basket_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('song_basket_association')
    op.drop_table('songs')
    op.drop_table('tokens')
    op.drop_table('song_baskets')
    op.drop_table('users')
    # ### end Alembic commands ###
