"""empty message

Revision ID: ba94359543a3
Revises: 39343ed659a8
Create Date: 2024-01-04 01:58:14.513738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba94359543a3'
down_revision = '39343ed659a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('track_uri', sa.String(), nullable=True))
        batch_op.drop_column('track_uris')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('track_uris', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('track_uri')

    # ### end Alembic commands ###
